//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Script1.rc
//
#define IDB_BITMAP1                     101
#define IDB_TILE                        103
#define IDR_MENU1                       104
#define IDD_GAMEEVENTS                  105
#define IDD_WINDOWSIZE                  106
#define IDD_DIALOG1                     107
#define IDD_CONTROLS                    107
#define IDB_LOGO                        110
#define IDI_ICON1                       111
#define IDD_ABOUT                       112
#define IDD_GAMEINFO                    113
#define IDR_COPYMENU                    114
#define IDR_ACCELERATOR1                117
#define IDD_MEMORY                      118
#define IDD_ITEMINFO                    122
#define IDB_BASE                        123
#define IDB_PILLBOX                     124
#define IDD_COMDLG32                    126
#define IDI_ICON2                       127
#define IDD_TEAMCOLOURS                 128
#define IDB_TANKS                       131
#define IDB_BOATS                       132
#define IDB_ITEMS                       134
#define IDD_DIALOG_FULLSCREEN           135
#define IDB_BITMAP2                     137
#define IDB_SPLASH                      137
#define IDD_TANKINFO                    140
#define IDB_TB_EVENTS                   150
#define IDD_BASEINFO                    151
#define IDC_LIST1                       1000
#define IDC_LIST                        1000
#define IDC_WIDTH                       1003
#define IDC_HEIGHT                      1004
#define IDC_LOGO                        1004
#define ID_REW                          1005
#define ID_PLAY                         1006
#define IDC_MAP_NAME                    1006
#define ID_PAUSE                        1007
#define IDC_NUM_PLAYERS                 1007
#define ID_FASTFORWARD                  1008
#define IDC_GAME_TYPE                   1008
#define ID_STOP                         1009
#define IDC_HIDDEN_MINES                1009
#define IDC_COMPUTER_TANKS              1010
#define ID_FORWARD                      1010
#define IDC_GAME_TIMELIMIT              1011
#define IDC_MEMORYEDIT                  1012
#define IDC_VERSION                     1012
#define IDC_WBN                         1013
#define IDC_PILLBOX                     1013
#define IDC_GAME_STARTDELAY             1014
#define IDC_BASE                        1015
#define IDC_CURRENT_TIME                1015
#define IDC_START_TIME                  1015
#define IDC_ITEM_TYPE                   1016
#define IDC_ITEM_OWNER                  1017
#define IDC_ITEM_SHELLS                 1018
#define IDC_ITEM_MINES                  1019
#define IDC_ITEM_ARMOUR                 1020
#define IDC_LOCATION                    1021
#define IDC_CENTRE_ON_MAP               1022
#define IDC_ITEM_INTANK                 1023
#define IDC_CHECKOWNERSHIP              1023
#define IDC_TEAM1                       1024
#define IDC_TEAM2                       1025
#define IDC_TEAM3                       1027
#define IDC_TEAM4                       1029
#define IDC_SPEED                       1029
#define IDC_TEAM5                       1030
#define IDC_SLIDER1                     1030
#define IDC_TEAM6                       1031
#define IDC_SS_X                        1031
#define IDC_TEAM7                       1032
#define IDC_SS_Y                        1032
#define IDC_SHELLS                      1032
#define IDC_TEAM8                       1033
#define IDC_MINES                       1033
#define IDC_TEAM9                       1034
#define IDC_ARMOR                       1034
#define IDC_TEAM10                      1035
#define IDC_RESOURCES                   1035
#define IDC_TEAM11                      1036
#define IDC_TANKINFO_PROGRESS_RESOURCES 1036
#define IDC_TEAM12                      1037
#define IDC_TANKINFO_PROGRESS_ARMOUR    1037
#define IDC_TEAM13                      1038
#define IDC_TANKINFO_PROGRESS_MINES     1038
#define IDC_TEAM14                      1039
#define IDC_TANKINFO_PROGRESS_SHELLS    1039
#define IDC_TEAM15                      1040
#define IDC_TEAM16                      1041
#define IDC_NEUTRAL                     1042
#define IDC_TANKINFO_TANKDEATHS         1046
#define IDC_TANKINFO_TANKKILLS          1047
#define IDC_TANKINFO_LGMDEATHS          1048
#define IDC_BASEINFO_SHELLS             1048
#define IDC_TANKINFO_LGMKILLS           1049
#define IDC_BASEINFO_MINES              1049
#define IDC_TANKINFO_BASECAPTURES       1050
#define IDC_BASEINFO_ARMOUR             1050
#define IDC_TANKINFO_PILLCAPTURES       1051
#define IDC_MAPS                        1089
#define IDC_PLAYERSS                    1090
#define IDC_GAMETS                      1091
#define IDC_HIDMINESS                   1092
#define IDC_COMPTANKSS                  1093
#define IDC_GAMETIMES                   1094
#define IDC_GAMETIMES2                  1095
#define IDC_GAMETIMES3                  1096
#define IDC_GAMETIMES4                  1097
#define IDC_GAMETIMES5                  1098
#define IDC_PLAYERSS2                   1098
#define ID_FILE_EXIT                    40001
#define ID_FILE_OPEN1                   40004
#define ID_ACTIONS_GO                   40005
#define ID_OPTIONS_WINDOWSIZE           40006
#define ID_ACTIONS_STOP                 40007
#define ID_HELP_ABOUT                   40008
#define ID_OPTIONS_SOUNDEFFECTS         40009
#define ID_WINDOWS_EVENTS               40010
#define ID_WINDOWS_CONTROLS             40011
#define ID_WINDOWS_STATUS               40012
#define ID_OPTIONS_TANK_CENTRED         40013
#define ID_COPY_COPY                    40014
#define ID_COPY_SELECTALL               40015
#define ID_OPTIONS_MEMORYBUFFER         40016
#define ID_WINDOWS_GAMEINFORMATION      40017
#define ID_WINDOWS_ITEMINFORMATION      40018
#define ID_ACTION_PLAY                  40019
#define ID_ACTION_PAUSE                 40020
#define ID_ACTION_STOP                  40021
#define ID_ACTION_FASTFORWARD           40022
#define ID_ACTION_REWIND                40023
#define ID_FILE_SAVEMAP                 40024
#define ID_OPTIONS_DNSLOOKUPS           40025
#define ID_OPTIONS_MODE_INFORMATION     40027
#define ID_OPTIONS_MODE_SELECTTEAM      40028
#define ID_OPTIONS_TEAMCOLOURS          40029
#define ID_OPTIONS_USETEAMCOLOURS       40031
#define ID_ACTION_FULLSCREEN            40034
#define ID_OPTIONS_MODE_FULLSCREEN      40035
#define ID_HELP_HELP                    40036
#define ID_WINDOWS_TANKINFORMATION      40037

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         40041
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
