//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDR_MENU1                       101
#define IDI_BOLO                        102
#define IDD_ABOUT                       103
#define IDC_POINTER                     104
#define IDB_ABOUT                       106
#define IDB_TILE                        107
#define IDB_BACKGROUND                  108
#define IDI_ICON1                       111
#define IDI_BSOUNDS                     117
#define IDC_BOLOCURSOR                  118
#define IDI_BMAP                        119
#define IDD_SYSTEM_INFO                 120
#define IDD_GAME_INFO                   121
#define IDD_GAME_SETUP                  123
#define IDD_OPENING                     124
#define IDD_KEY_SETUP                   126
#define IDD_SETPLAYERNAME               127
#define IDR_ACCELERATOR                 128
#define IDD_MESSAGES                    129
#define IDD_TCPIP_SETUP                 130
#define IDD_PASSWORD                    131
#define IDD_NETWORK_INFO                132
#define IDB_LOGOSMALL                   143
#define IDD_TRACKERSETUP                144
#define IDI_BRAIN                       147
#define IDD_GAMEFINDER                  149
#define STR_DLGOPENING_TITLE            151
#define IDD_LANGUAGES                   151
#define STR_DLGOPENING_TEXT             152
#define STR_DLGOPENING_OPTION1          153
#define STR_DLGOPENING_OPTION2          154
#define STR_DLGOPENING_OPTION3          155
#define IDR_RC_DATA1                    155
#define STR_DLGOPENING_SKIP             156
#define STR_OK                          157
#define IDR_MAPS1                       157
#define STR_DLGOPENING_BUTTON2          158
#define IDR_TUTORIAL                    158
#define STR_DLGLANG_TITLE               159
#define STR_DLGLANG_NAME_CAPTION        160
#define STR_DLGLANG_NAME                161
#define STR_DLGLANG_AUTHOR_CAPTION      162
#define STR_DLGLANG_AUTHOR              163
#define IDR_EVERARD                     163
#define STR_DLGOPENING_OPTION4          164
#define STR_DLGOPENING_OPTION0          165
#define STR_DLGLANG_NOTES_CAPTION       166
#define STR_DLGLANG_NOTES               167
#define STR_DLGLANG_DEFAULTNOTE         168
#define STR_DLGABOUT_TITLE              169
#define STR_DLGABOUT_BLURB              170
#define STR_DLGALLIANCE_TITLE           171
#define IDR_MAPS2                       171
#define STR_DLGALLIANCE_ACCEPT          172
#define IDD_ALLIANCE                    172
#define STR_DLGALLIANCE_DECLINE         173
#define IDD_COMDLG32                    173
#define STR_DLGALLIANCE_BLURB           174
#define STR_DLGGAMEFINDER_REFRESHFIRST  175
#define STR_DLGGAMEFINDER_MESSAGEOFTHEDAY 176
#define STR_DLGGAMEFINDER_WRONGVERSION  177
#define STR_DLGGAMEFINDER_NOGAMESINPROGRESS 178
#define IDD_WINBOLONET                  178
#define STR_YES                         179
#define STR_NO                          180
#define IDD_SKINS                       180
#define STR_DLGGAMEFINDER_YESADV        181
#define STR_DLGGAMEFINDER_OPEN          182
#define STR_DLGGAMEFINDER_TOURNAMENT    183
#define STR_DLGGAMEFINDER_STRICTTOURNAMENT 184
#define STR_DLGGAMEINFO_TITLE           185
#define IDB_BITMAP1                     185
#define STR_DLGGAMEINFO_MAPNAME         186
#define IDB_BITMAP2                     186
#define STR_DLGGAMEINFO_NUMPLAYERS      187
#define IDR_MAP1                        187
#define STR_DLGGAMEINFO_GAMETYPE        188
#define STR_DLGGAMEINFO_HIDDENMINES     189
#define STR_DLGGAMEINFO_ALLOWCOMPTANKS  190
#define STR_DLGGAMEINFO_TIMELIMIT       191
#define STR_DLGGAMESETUP_BLURB          192
#define STR_CANCEL                      193
#define STR_DLGGAMESETUP_TITLE          194
#define STR_DLGGAMESETUP_CHOOSEMAP      195
#define STR_DLGGAMESETUP_SELECTEDMAP    196
#define STR_DLGGAMESETUP_SELECTEDMAPINBUILT 197
#define STR_DLGGAMESETUP_RADIO1         198
#define STR_DLGGAMESETUP_RADIO2         199
#define STR_DLGGAMESETUP_RADIO3         200
#define STR_DLGGAMESETUP_HIDDENMINES    201
#define STR_DLGGAMESETUP_ALLOWCOMPTANKS 202
#define STR_DLGGAMESETUP_ALLOWCOMPTANKSADV 203
#define STR_DLGGAMESETUP_PASSWORD       204
#define STR_DLGGAMESETUP_MINUTES        205
#define STR_DLGGAMESETUP_SECONDS        206
#define STR_DLGGAMESETUP_STARTDELAY     207
#define STR_DLGGAMESETUP_TIMELIMIT      208
#define STR_DLGGAMESETUP_ERROROPENINGMAP 209
#define STR_DLGGAMEINFO_TIMEREMAINING   210
#define STR_DLGGAMEINFO_OPEN            211
#define STR_DLGGAMEINFO_TOURN           212
#define STR_DLGGAMEINFO_STRICT          213
#define STR_DLGGAMEINFO_AIADV           214
#define STR_DLGGAMESETUP_DEFAULTNAME    215
#define STR_DLGKEYSETUP_TITLE           216
#define STR_DLGKEYSETUP_BLURB           217
#define STR_DLGKEYSETUP_DRIVETANK       218
#define STR_DLGKEYSETUP_TURNTANK        219
#define STR_DLGKEYSETUP_GUNRANGE        220
#define STR_DLGKEYSETUP_WEAPONS         221
#define STR_DLGKEYSETUP_VIEW            222
#define STR_DLGKEYSETUP_SCROLL          223
#define STR_DLGKEYSETUP_LEFT            224
#define STR_DLGKEYSETUP_RIGHT           225
#define STR_DLGKEYSETUP_AUTOSLOWDOWN    226
#define STR_DLGKEYSETUP_AUTOGUNSIGHT    227
#define STR_DLGKEYSETUP_FASTER          228
#define STR_DLGKEYSETUP_SLOWER          229
#define STR_DLGKEYSETUP_TURNLEFT        230
#define STR_DLGKEYSETUP_TURNRIGHT       231
#define STR_DLGKEYSETUP_INCREASE        232
#define STR_DLGKEYSETUP_DECREASE        233
#define STR_DLGKEYSETUP_SHOOT           234
#define STR_DLGKEYSETUP_LAYMINE         235
#define STR_DLGKEYSETUP_TANKVIEW        236
#define STR_DLGKEYSETUP_PILLVIEW        237
#define STR_DLGKEYSETUP_SCROLLUP        238
#define STR_DLGKEYSETUP_SCROLLDOWN      240
#define STR_DLGKEYSETUP_SCROLLLEFT      241
#define STR_DLGKEYSETUP_SCROLLRIGHT     242
#define STR_DLGKEYSETUP_NEWKEYFOR       243
#define STR_DLGKEYSETUP_FORWARD         244
#define STR_DLGKEYSETUP_BACKWARD        245
#define STR_DLGKEYSETUP_ROTATELEFT      246
#define STR_DLGKEYSETUP_ROTATERIGHT     247
#define STR_DLGKEYSETUP_INCREASERANGE   248
#define STR_DLGKEYSETUP_DECREASERANGE   249
#define STR_DLGKEYSETUP_SETSHOOT        250
#define STR_DLGKEYSETUP_SETLAYMINE      251
#define STR_DLGKEYSETUP_SETTANKVIEW     252
#define STR_DLGKEYSETUP_SETPILLVIEW     253
#define STR_DLGKEYSETUP_SETSCROLLUP     254
#define STR_DLGKEYSETUP_SETSCROLLDOWN   255
#define STR_DLGKEYSETUP_SETSCROLLLEFT   256
#define STR_DLGKEYSETUP_SETSCROLLRIGHT  257
#define STR_DLGMSG_BUTTON               258
#define STR_DLGMSG_ALLPLAYERS           259
#define STR_DLGMSG_ALLALLIES            260
#define STR_DLGMSG_NEARBY               261
#define STR_DLGMSG_SELECTION            262
#define STR_DLGMSG_SENDPLAYER           263
#define STR_DLGMSG_SENDPLAYERS          264
#define STR_DLGNETINFO_TITLE            265
#define STR_DLGNETINFO_SERVERADDRESS    266
#define STR_DLGNETINFO_THISGAMEADDRESS  267
#define STR_DLGNETINFO_SERVERPING       268
#define STR_DLGNETINFO_PACKETS          269
#define STR_DLGNETINFO_STATUS           270
#define STR_DLGNETINFO_ERRORS           271
#define STR_DLGPASSWORD_TITLE           272
#define STR_DLGPASSWORD_BLURB           273
#define STR_DLGSETNAME_TITLE            274
#define STR_DLGSETNAME_BLURB            275
#define STR_DLGTRACKER_TITLE            276
#define STR_DLGTRACKER_USETRACKER       277
#define STR_DLGTRACKER_TRACKERADDRESS   278
#define STR_DLGTRACKER_TRACKERPORT      279
#define STR_DLGSYSINFO_TITLE            280
#define STR_DLGSYSINFO_CPUUSAGE         281
#define STR_DLGSYSINFO_SIMMODELING      282
#define STR_DLGSYSINFO_COMPROCESSING    283
#define STR_DLGSYSINFO_GRAHPICSDISPLAY  284
#define STR_DLGSYSINFO_AICONTROLPROCESSING 285
#define STR_DLGSYSINFO_TOTAL            286
#define STR_DLGSYSINFO_GRAPHICSFPS      287
#define STR_DLGTCP_TITLE                288
#define STR_DLGTCP_BLURB                289
#define STR_DLGTCP_JOIN                 290
#define STR_DLGTCP_REJOIN               291
#define STR_DLGTCP_NEW                  292
#define STR_DLGTCP_TRACKERSETUP         293
#define STR_DLGTCP_REMEMBER             294
#define STR_DLGTCP_MACHINENAME          295
#define STR_DLGTCP_THEREUDP             296
#define STR_DLGTCP_USUDP                297
#define STR_DLGTCP_NAME                 298
#define STR_DLGTCP_NEWBLURB             299
#define STR_DLGTCP_JOINBLURB            300
#define STR_DLGTCP_REJOINBLURB          301
#define STR_ERR_DLGTCP_PORTS            302
#define STR_ERR_DLGTCP_NOTRIGHT         303
#define STR_ERR_DLGTCP_SUBCLASS         304
#define STR_DLGGAMEFINDER_JOINADDRESS   305
#define STR_DLGGAMEFINDER_REFRESH       306
#define STR_DLGGAMEFINDER_PLAYERNAME    307
#define STR_DLGGAMEFINDER_MOTD          308
#define STR_DLGGAMEFINDER_STATUSBLURB   309
#define STR_DLGGAMEFINDER_SELECTEDGAME  310
#define STR_DLGGAMEFINDER_BRAINS        311
#define STR_DLGGAMEFINDER_PASSWORD      312
#define STR_DLGGAMEFINDER_PILLS         313
#define STR_DLGGAMEFINDER_BASES         314
#define STR_DLGGAMEFINDER_HIDDENMINES   315
#define STR_DLGGAMEFINDER_NUMPLAYERS    316
#define STR_DLGGAMEFINDER_VERSION       317
#define STR_DLGGAMEFINDER_GAMETYPE      318
#define STR_DLGGAMEFINDER_PORT          319
#define STR_DLGGAMEFINDER_ADDRESS       320
#define STR_BRAINERR_BRAINDIR           321
#define STR_BRAINERR_LAUNCH             322
#define STR_BRAINERR_LAUNCHMAIN         323
#define STR_BRAINERR_INIT               324
#define STR_BRAINERR_EXEC               325
#define STR_DRAWERROR_CREATEOBJECT      326
#define STR_DRAWERROR_SETCOOPLEVEL      327
#define STR_DRAWERROR_CREATEPRIMARY     328
#define STR_DRAWERROR_GETPIXELFORMAT    329
#define STR_DRAWERROR_GETDESC           330
#define STR_DRAWERROR_TOOFEWCOLOURS     331
#define STR_DRAWERROR_BUFFERCREATE      332
#define STR_DRAWERROR_GETDCFAILED       333
#define STR_DRAWERROR_CLIPPERFAILED     334
#define STR_DRAWERROR_BRUSH             335
#define STR_DRAWERROR_PEN               336
#define STR_DRAW_GAMESTARTSIN           337
#define STR_DRAWERROR_RELEASEDC         338
#define STR_DRAW_PILLBOXVIEW            339
#define STR_FONTERR_NOCOURIERFONT       340
#define STR_GAMEFRONTERR_CORRUPTPREFS   341
#define STR_GAMEFRONTERR_WINDOW         342
#define STR_GAMEFRONTERR_DDRAW          343
#define STR_GAMEFRONTERR_DSOUND         344
#define STR_GAMEFRONTERR_DINPUT         345
#define STR_GAMEFRONTERR_CURSOR         346
#define STR_GAMEFRONTERR_FONTS          347
#define STR_GAMEFRONT_LANFINDER_TITLE   348
#define STR_GAMEFRONT_TRACKERFINDER_TITLE 349
#define STR_GAMEFRONTERR_JOINGAME       350
#define STR_GAMEFRONTERR_SPAWNSERVER    351
#define STR_GAMEFRONTERR_NETSINGLEPLAYER 352
#define STR_GAMEFRONT_SERVERSTARTMSG    353
#define STR_GAMEFRONT_INPUTERR_CREATE   354
#define STR_GAMEFRONT_INPUTERR_DATAFORMAT 355
#define STR_GAMEFRONT_INPUTERR_COOPLEVEL 356
#define STR_NETCLIENTERR_WINSOCKFAILSTARTUP 357
#define STR_NETCLIENTERR_CREATEUDPFAIL  358
#define STR_NETCLIENTERR_CREATETCPFAIL  359
#define STR_NETCLIENTERR_BINDUDPFAIL    360
#define STR_NETCLIENTERR_CHAINFAIL      361
#define STR_NETCLIENTERR_TRACKERVERSIONFAIL 362
#define STR_NETCLIENTERR_TRACKERDNSFAIL 363
#define STR_NETCLIENTERR_TRACKERCONNECTFAIL 364
#define STR_NETCLIENTERR_TRACKERNOBLOCK 365
#define STR_NETCLIENT_TRACKERGETRESPONSE 366
#define STR_NETCLIENT_TRACKERPROCESSRESPONSE 367
#define STR_NETCLIENTERR_TRACKERNODATA  368
#define STR_NETCLIENT_TRACKERCONNECT    369
#define STR_NETCLIENT_IDLE              370
#define STR_NETCLIENTERR_BIND           371
#define STR_NETCLIENTERR_BROADCAST      372
#define STR_NETCLIENT_GETRESPONSES      373
#define STR_SOUNDERR_FILENOTFOUND       374
#define STR_SOUNDERR_HARDWAREINUSE      375
#define STR_SOUNDERR_CREATEFAILED       376
#define STR_SOUNDERR_COOPFAILED         377
#define STR_SOUNDERR_PRIMARYBUFFFAIL    378
#define STR_SOUNDERR_LOADSOUNDFAILED    379
#define STR_WBERR_MUTEXCREATE           380
#define STR_WBERR_BRAINLISTLOAD         381
#define STR_WBERR_KEYCLASSSETUP         382
#define STR_WBTIMELIMIT_END             383
#define STR_WBERR_SAVEMAP               384
#define STR_TUTORIAL01                  385
#define STR_TUTORIAL02                  386
#define STR_TUTORIAL03                  387
#define STR_TUTORIAL04                  388
#define STR_TUTORIAL05                  389
#define STR_TUTORIAL06                  390
#define STR_TUTORIAL07                  391
#define STR_TUTORIAL08                  392
#define STR_TUTORIAL09                  393
#define STR_TUTORIAL10                  394
#define STR_TUTORIAL11                  395
#define STR_TUTORIAL12                  396
#define STR_TUTORIAL13                  397
#define STR_TUTORIAL14                  398
#define STR_TUTORIAL15                  399
#define STR_TUTORIAL16                  400
#define STR_TUTORIAL17                  401
#define STR_TUTORIAL18                  402
#define STR_TUTORIAL19                  403
#define STR_TUTORIAL20                  404
#define STR_TUTORIAL21                  405
#define STR_TUTORIAL22                  406
#define STR_TUTORIAL23                  407
#define STR_TUTORIAL24                  408
#define STR_TUTORIAL25                  409
#define STR_TUTORIAL_START01            410
#define STR_TUTORIAL_START02            411
#define STR_TUTORIAL_START03            412
#define STR_TUTORIAL_START04            413
#define LGM_MAN_DEAD                    414
#define LGM_NO_BUILD                    415
#define LGM_INSUFFICIENT_TREES          416
#define LGM_NO_PILLS                    417
#define LGM_INSUFFICIENT_MINES          418
#define LGM_BUILDTANK                   419
#define LGM_NO_TREE                     420
#define LGM_PILL_NO_NEED_REPAIR         430
#define LGM_PILL_NO_BUILD_ON_MINE       431
#define MESSAGE_ASSISTANT               432
#define MESSAGE_NEWSWIRE                433
#define MESSAGE_AI                      434
#define MESSAGE_CHANGENAME              435
#define MESSAGE_NETSERVER               436
#define MESSAGE_THIS_COMPUTER           437
#define MESSAGE_CAPTURE_BASE            438
#define MESSAGE_CAPTURE_PILL            439
#define MESSAGE_STOLE_PILL              440
#define MESSAGE_STOLE_BASE              441
#define MESSAGE_LGM_DEAD                442
#define MESSAGE_SAVED_MAP               443
#define MESSAGE_QUIT_GAME               444
#define MESSAGE_TIME_LIMIT_EXPIRED      445
#define MESSAGE_TANKSUNK                446
#define NETERR_TRACKERDNS               447
#define NETERR_JOININIT                 448
#define NETERR_GAMEFULL                 449
#define NETERR_SERVERCONNECT            450
#define NETERR_PASSWORDWRONG            451
#define NETERR_PLAYERNAMEINUSE          452
#define NETERR_NONEWPLAYERS             453
#define NETERR_CONNECTNOJOIN            454
#define NET_STATUS_JOINING              455
#define NET_STATUS_OK                   456
#define NET_STATUS_FAILED               457
#define NETERR_LOSTCONNECTION           458
#define STR_DLGMSG_TITLE                459
#define STR_DLGOPENING_BUTTON3          460
#define STR_DLGOPENING_BUTTON4          461
#define STRERR_HELPFILE                 462
#define STR_DLGSKIN_TITLE               463
#define STR_DLGSKIN_DEFAULTNOTE         464
#define IDC_STATIC1                     1003
#define IDC_FPSS                        1003
#define IDC_FRAME_RATE                  1005
#define IDC_MAP_NAME                    1006
#define IDC_NUM_PLAYERS                 1007
#define IDC_GAME_TYPE                   1008
#define IDC_SKIP_DIALOG                 1008
#define IDC_HIDDEN_MINES                1009
#define IDC_GAMETYPE1                   1009
#define IDC_GAMETYPE00                  1009
#define IDC_COMPUTER_TANKS              1010
#define IDC_GAMETYPE2                   1010
#define IDC_GAMETYPE01                  1010
#define IDC_GAME_TIMELIMIT              1011
#define IDC_CHOOSE_MAP                  1011
#define IDC_GAMETYPE0                   1011
#define IDC_GAMETYPE02                  1011
#define IDC_SELECTEDMAP                 1012
#define IDC_GAMETYPE3                   1012
#define IDC_RADIO1                      1013
#define IDC_GAMETYPE4                   1013
#define IDC_RADIO2                      1014
#define IDC_RADIO3                      1015
#define IDC_ALLOWCOMP1                  1017
#define IDC_ALLOWCOMP2                  1018
#define IDC_CHECKPASS                   1019
#define IDC_EDITPASS                    1020
#define IDC_GAMESTART                   1021
#define IDC_EDITSTART                   1022
#define IDC_CHECKTIME_LIMIT             1023
#define IDC_EDITTIMELIMIT               1024
#define IDC_OK                          1025
#define IDC_GRAPHICS                    1027
#define IDC_SIM                         1028
#define IDC_COMMUNICATION               1029
#define IDC_AI                          1030
#define IDC_TOTAL                       1031
#define IDC_CACCEL                      1031
#define IDC_CDECEL                      1032
#define IDC_CLEFT                       1033
#define IDC_CRIGHT                      1034
#define IDC_AUTOSLOWDOWN                1035
#define IDC_CINCREASE                   1036
#define IDC_CDECREASE                   1037
#define IDC_ACCEL                       1038
#define IDC_DECEL                       1039
#define IDC_LEFT                        1040
#define IDC_RIGHT                       1041
#define IDC_INCREASE                    1042
#define IDC_DECREASE                    1043
#define IDC_CSHOOT                      1044
#define IDC_CLAYMINE                    1045
#define IDC_SHOOT                       1046
#define IDC_LAYMINE                     1047
#define IDC_CTANKVIEW                   1048
#define IDC_CPILLVIEW                   1049
#define IDC_TANKVIEW                    1050
#define IDC_PILLVIEW                    1051
#define IDC_CSCROLLUP                   1052
#define IDC_CSCROLLDOWN                 1053
#define IDC_SCROLLUP                    1054
#define IDC_SCROLLDOWN                  1055
#define IDC_CSCROLLLEFT                 1056
#define IDC_CSCROLLRIGHT                1057
#define IDC_SCROLLLEFT                  1058
#define IDC_SCROLLRIGHT                 1059
#define IDC_AUTOGUNSIGHT                1060
#define IDC_EDITNAME                    1064
#define ID_SEND                         1065
#define IDC_EDITSEND                    1066
#define ID_JOIN                         1067
#define ID_NEW                          1068
#define IDC_EDITIP                      1069
#define IDC_UDP                         1070
#define IDC_MYUDP                       1071
#define IDC_PLAYERNAME                  1072
#define IDC_CHECK_REMEMBER              1073
#define IDC_PASSWORD                    1074
#define ID_REJOIN                       1074
#define IDC_UPSTREAM                    1075
#define IDC_SERVER                      1075
#define IDC_BRAINS                      1075
#define IDC_THISADDRESS                 1076
#define IDC_ALL_PLAYERS                 1076
#define IDC_DOWNSTREAM                  1077
#define IDC_ALL_ALLIES                  1077
#define IDC_TRACKERADDRESS              1077
#define IDC_DOWNSTREAMDELAY             1078
#define IDC_ALL_NEARBY                  1078
#define IDC_PING                        1078
#define IDC_TRACKERPORT                 1078
#define IDC_TOTALDELAY                  1079
#define IDC_ALL_SELECTION               1079
#define IDC_USETRACKER                  1079
#define IDC_PACKETSPERSECOND            1080
#define IDC_TRACKER                     1080
#define IDC_NETSTATUS                   1081
#define IDC_MESSAGE                     1081
#define IDC_NETERRORS                   1082
#define IDC_JOINADDRESS                 1082
#define IDC_RETRANSMITTED               1083
#define IDC_REFRESH                     1083
#define IDC_SETPLAYERNAME               1084
#define IDC_NEW                         1085
#define IDC_LIST                        1086
#define IDC_SERVERADDRESS               1087
#define IDC_PORT                        1088
#define IDC_BLURB                       1088
#define IDC_MAPNAME                     1089
#define IDC_MAPS                        1089
#define IDC_VERSION                     1090
#define IDC_PLAYERSS                    1090
#define IDC_NOPLAYERS                   1091
#define IDC_GAMETS                      1091
#define IDC_FREEBASES                   1092
#define IDC_HIDMINESS                   1092
#define IDC_FREEPILLS                   1093
#define IDC_COMPTANKSS                  1093
#define IDC_MINES                       1094
#define IDC_GAMETIMES                   1094
#define IDC_GAMETYPE                    1095
#define IDC_SECONDS                     1095
#define IDC_MINUTES                     1096
#define IDC_REJOIN                      1096
#define IDC_LEFTS                       1097
#define IDC_RIGHTS                      1098
#define IDC_DRIVES                      1099
#define IDC_ROTATES                     1100
#define IDC_GUNRANGES                   1101
#define IDC_WEAPONS                     1102
#define IDC_VIEWS                       1103
#define IDC_SCROLLS                     1104
#define IDC_SERVERS                     1105
#define IDC_THISADDRESSS                1106
#define IDC_SERVERPINGS                 1107
#define IDC_PPSPLS                      1108
#define IDC_NETSTATUSS                  1109
#define IDC_NETERRORSS                  1110
#define IDC_CPUUSAGES                   1111
#define IDC_SIMMODELS                   1112
#define IDC_COMPROCESSS                 1113
#define IDC_GRAPHICSDISPLAYS            1114
#define IDC_AITANKS                     1115
#define IDC_TOTALS                      1116
#define IDC_ADDRESSS                    1117
#define IDC_THEREUDPS                   1118
#define IDC_OURUDPS                     1119
#define IDC_PLAYERNAMES                 1120
#define IDC_NEWS                        1121
#define IDC_JOINS                       1122
#define IDC_TRACKERADDRESSS             1123
#define IDC_REJOINS                     1123
#define IDC_TRACKERPORTS                1124
#define IDC_LIST1                       1125
#define IDC_LANGNAMES                   1126
#define IDC_LANGNAME                    1127
#define IDC_DEFAULT                     1128
#define IDC_AUTHORS                     1129
#define IDC_LANG                        1129
#define IDC_AUTHOR                      1130
#define IDC_FRAME                       1130
#define IDC_OPENINGHELP                 1130
#define IDC_NOTESS                      1131
#define IDC_SADRESS                     1131
#define IDC_WBNSETUP                    1131
#define IDC_NOTES                       1132
#define IDC_SPORT                       1132
#define IDC_SKINSSETUP                  1132
#define IDC_VERSIONS                    1133
#define IDC_MAPNAMES                    1134
#define IDC_NOPLAYERSS                  1135
#define IDC_GAMETYPES                   1136
#define IDC_FREEBASESS                  1137
#define IDC_FREEPILLSS                  1138
#define IDC_HIDMINES                    1139
#define IDC_PASSS                       1140
#define IDC_BRAINSS                     1141
#define IDC_STATUSS                     1142
#define IDC_STATUS                      1143
#define IDC_LABEL                       1143
#define IDC_INFO                        1144
#define IDC_MAP                         1148
#define IDC_USEWBN                      1150
#define IDC_SAVEPASS                    1151
#define IDC_WBNPASS                     1152
#define IDC_WBNMORE                     1153
#define IDC_WBNNAME                     1154
#define IDC_SKINNAMES                   1155
#define IDC_SKINNAME                    1156
#define IDC_SKINNOTES                   1157
#define IDC_SKINAUTHOR                  1158
#define IDC_SKINLIST                    1159
#define IDC_SKINDEFAULT                 1160
#define IDC_SKINAUTHORS                 1161
#define IDC_SKINNOTESS                  1162
#define IDR_MENU2                       32000
#define ID_FG_SDF                       32001
#define ID_HELP_ABOUT                   40001
#define ID_HELPMENU_ABOUT               40001
#define ID_FILE_EXIT                    40003
#define ID_FILEMENU_EXIT                40003
#define ID_FILEMENU_OPEN                40004
#define ID_FRAMERATEMENU_10             40005
#define ID_FRAMERATEMENU_15             40006
#define ID_FRAMERATEMENU_30             40007
#define ID_FRAMERATEMENU_50             40008
#define ID_FRAMERATEMENU_60             40009
#define ID_FRAMERATEMENU_20             40010
#define ID_FRAMERATEMENU_12             40011
#define ID_EDITMENU_GUNSIGHT            40012
#define ID_BOLOMENU_SOUNDEFFECTS        40014
#define ID_BOLOMENU_BACKGROUNDSOUND     40015
#define ID_BOLOMENU_ISASOUNDCARD        40016
#define ID_BOLOMENU_NEWSWIREMESSAGES    40017
#define ID_BOLOMENU_ASSISTANTMESSAGES   40018
#define ID_BOLOMENU_AIBRAINMESSAGES     40019
#define ID_BOLOMENU_NETWORKSTATUSMESSAGES 40020
#define ID_EDITMENU_AUTOMATICSCROLLING  40022
#define ID_WINDOWSIZE_NORMAL            40025
#define ID_WINDOWSIZE_DOUBLE            40026
#define ID_WINDOWSIZE_QUAD              40027
#define ID_EDITMENU_PILLLABELS          40028
#define ID_EDITMENU_BASELABELS          40029
#define ID_FILEMENU_SYSTEMINFO          40030
#define ID_FILEMENU_GAMEINFO            40031
#define ID_FILEMENU_NEW                 40032
#define ID_BOLOMENU_SETKEYS             40033
#define ID_BOLOMENU_CHANGENAME          40035
#define ID_EDIT_MESSAGESENDERNAMES_SHORT 40037
#define ID_EDIT_MESSAGESENDERNAMES_LONG 40038
#define ID_EDIT_TANKLABELS_NONE         40039
#define ID_EDIT_TANKLABELS_SHORT        40040
#define ID_EDIT_TANKLABELS_LONG         40041
#define ID_EDIT_TANKLABELS_DONTLABELOWNTANK 40042
#define ID_PLAYERSMENU_SENDMESSAGE      40044
#define ID_PLAYERSMENU_SELECTALL        40045
#define ID_PLAYERSMENU_SELECTNONE       40046
#define ID_PLAYERSMENU_SELECTALLIES     40047
#define ID_PLAYERSMENU_SELECTNEARBYTANKS 40048
#define ID_PLAYERSMENU_01               40049
#define ID_PLAYERSMENU_02               40050
#define ID_PLAYERSMENU_03               40051
#define ID_PLAYERSMENU_04               40052
#define ID_PLAYERSMENU_05               40053
#define ID_PLAYERSMENU_06               40054
#define ID_PLAYERSMENU_07               40055
#define ID_PLAYERSMENU_08               40056
#define ID_PLAYERSMENU_09               40057
#define ID_PLAYERSMENU_10               40058
#define ID_PLAYERSMENU_11               40059
#define ID_PLAYERSMENU_12               40060
#define ID_PLAYERSMENU_13               40061
#define ID_PLAYERSMENU_14               40062
#define ID_PLAYERSMENU_15               40063
#define ID_PLAYERSMENU_16               40064
#define ID_FILEMENU_SAVEMAP             40065
#define ID_FILEMENU_NETWORKINFO         40066
#define ID_EDITMENU_HIDEMAINVIEW        40067
#define ID_BOLOMENU_REQUESTALLIENCE     40068
#define ID_BOLOMENU_LEAVEALLIENCE       40069
#define ID_BRAINSMENU_MANUAL            40070
#define ID_BOLOMENU_ALLOWNEWPLAYERS     40076
#define ID_BOLOMENU_NETWORKDEBUGMESSAGES 40077
#define ID_HELP_HELP                    40078
#define ID_BOLOMENU_REQUESTALLIANCE     40080

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         40081
#define _APS_NEXT_CONTROL_VALUE         1163
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
